# Docker Benchmark Configuration

[benchmark]
duration = 30
warmup_duration = 5

[[servers]]
server_type = "Furnace"
image = "furnace:latest"
port = 3000
pull_policy = "Never"

[servers.environment]
MODEL_PATH = "/app/models/model.mpk"

[servers.resource_limits]
cpu_limit = "1.0"
memory_limit = "512Mi"

[[models]]
name = "mnist_model"
size_category = "Small" 
model_type = "ImageClassification"
input_shape = [784]

[models.formats]
Furnace = "/app/models/model.mpk"

[[load_patterns]]
pattern_type = "Constant"
requests_per_second = 10
duration = 30